# -*- coding: utf-8 -*-
"""Actividad1POO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvMIZVg6w-qPRSlrNqirVMEC-HMz-0_k
"""

class Edades:
    def calcular_edalber(edjuan):
        return 2 * edjuan / 3

    def calcular_edana(edjuan):
        return 4 * edjuan / 3

    def calcular_edmama(edjuan, edalber, edana):
        return edjuan + edalber + edana


class Main:
    def main():
        edjuan = float(input("Ingrese la edad de juan: "))

        edalber = Edades.calcular_edalber(edjuan)
        edana = Edades.calcular_edana(edjuan)
        edmama = Edades.calcular_edmama(edjuan, edalber, edana)

        print("Edad de Juan:", edjuan)
        print("Edad de Alberto:", edalber)
        print("Edad de Ana:", edana)
        print("Edad de mama:", edmama)

Main.main()

import math


class Circulo:
   def calcular_area(radio):
        return math.pi * radio ** 2
   def calcular_circunferencia(radio):
        return 2 * math.pi * radio


class Main:
    def main():
        radio = float(input("Ingrese el radio del círculo: "))

        area = Circulo.calcular_area(radio)
        circunferencia = Circulo.calcular_circunferencia(radio)

        print("El área del círculo es:", area)
        print("La longitud de la circunferencia es:", circunferencia)


Main.main()

class operaciones:
    def operacion_suma1(suma,x):
      return suma + x
    def operacion_suma2(x,y):
      return x + y**2
    def operacion_suma3(suma,x,y):
      return suma + x/y
class Main:
    def main():
        suma = 0
        x = 20
        suma = operaciones.operacion_suma1(suma,x)
        y = 40
        x = operaciones.operacion_suma2(x,y)
        suma = operaciones.operacion_suma3(suma,x,y)
        print("El valos de la suma es:",suma)


Main.main()

class Salario:
    def calcular_bruto(horas, valor_hora):
        return horas * valor_hora
    def calcular_retencion(bruto, porcentaje):
        return bruto * porcentaje / 100
    def calcular_neto(bruto, retencion):
        return bruto - retencion


class Main:
    def main():
        horas = 48
        valor_hora = 5000
        porcentaje_retencion = 12.5

        bruto = Salario.calcular_bruto(horas, valor_hora)
        retencion = Salario.calcular_retencion(bruto, porcentaje_retencion)
        neto = Salario.calcular_neto(bruto, retencion)

        print("Salario bruto:", bruto)
        print("Retención en la fuente:", retencion)
        print("Salario neto:", neto)


Main.main()

class Calculadora:

    def calcular_cuadrado(numero):
        return numero ** 2
    def calcular_cubo(numero):
        return numero ** 3

class Main:
    def main():
        numero = float(input("Ingrese un número: "))

        cuadrado = Calculadora.calcular_cuadrado(numero)
        cubo = Calculadora.calcular_cubo(numero)

        print("Numero:",numero)
        print("Cuadrado:",cuadrado)
        print("Cubo:",cubo)


Main.main()